spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://db4free.net:3306/challengeAvalith
#    username: root
#    password: karina2020

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
